version: '3'


services:
  paises-micro:
    build: ../parcial-1-countries-api-405063-zarza-mateo
    image: paises-app
    ports:
      - "8080:8080"
    environment:
      APP_NAME: paises-app
    depends_on:
      - apiExterna
    networks:
      - paises-network

  apiExterna:
    image: https://restcountries.com/v3.1/all
    ports:
      - "8084:8080"
    networks:
      - paises-network

networks:
  paises-network:
    driver: bridge
